#!/bin/bash
WLANPSK=$(dd if=/dev/urandom count=1 status=none|tr -d -c 'a-z'|cut -b1-10)
sed -ie "s/wpa_passphrase=.*/wpa_passphrase=${WLANPSK}/" /etc/hostapd/hostapd.conf
service hostapd reload

qrencode -t PNG -o - -s 4 "WIFI:T:WPA;S:WLAN-Butler;P:${WLANPSK};H:false;" | convert - /var/guestwlan/android.jpg
qrencode -t PNG -o - -s 4 "WIFI;T:WPA;S:WLAN-Butler;P:${WLANPSK};H:false;" | convert - /var/guestwlan/windows.jpg
sed -e "s/<string>wlanpsk/<string>${WLANPSK}/" /var/www/html/gaestewlan.mobileconfig.in > /var/www/html/${WLANPSK}.mobileconfig
qrencode -t PNG -o - -s 4 "http://my.example.com/${WLANPSK}.mobileconfig" | convert - /var/guestwlan/ios.jpg

cat > /var/guestwlan/wlan.cfg <<EOF
[WLAN]
wlanssid=WLAN-Butler
wlanpsk=${WLANPSK}
EOF
